---
- hosts: 172.31.43.123
  become: yes
  tasks:
  - name: i want to execute linux command directly by playbook
    command: hostname -f
    register: myresult

  - name: i wanto display my first task result
    debug:
       msg:"{{myresult}}"

