---
- hosts: 172.31.43.123 

  become: yes
  vars:
     myvars1: git
     myvars2: tree
     myvars3: wget
  tasks:
  - name: install tree
    apt:
      name: "{{myvars1}}"
  - name: i want to display myvars1
    debug:
       msg: "{{myvars1}}"

