---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver on only anible ubuntu node
    apt:
      name: apache2 
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on only ansible unbuntu node
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"


  - name: i want to start webserver on only ansible Redhat node
    yum: 
    name: httpd
    state: present
    when: ansible_os_family =="Redhat"

  - name: i want to start webserver on only ansible redhat node
    service:
    name: httpd
    when: ansible_os_family =="Redhat" 




